apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ecom-app
  namespace: ecom-app
spec:
  replicas: 4
  strategy:
    blueGreen:
      activeService: ecom-active
      previewService: ecom-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 300
      prePromotionAnalysis:
        templates:
        - templateName: ecom-success-rate
  selector:
    matchLabels:
      app: ecom-app
  template:
    metadata:
      labels:
        app: ecom-app
    spec:
      containers:
      - name: ecom-app
        image: registry.k8s.io/echoserver:1.10
        ports:
        - containerPort: 80
